# Generated by Django 5.2.10 on 2026-01-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Atributo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tipo de Atributo',
                'verbose_name_plural': 'Tipos de Atributo',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rotation', models.CharField(choices=[('A', 'Alta Rotação'), ('B', 'Média Rotação'), ('C', 'Baixa Rotação')], default='B', max_length=1)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU Base')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('product_type', models.CharField(choices=[('SIMPLE', 'Produto Simples'), ('VARIABLE', 'Produto Variável')], default='SIMPLE', max_length=10, verbose_name='Tipo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('uom', models.CharField(default='UN', max_length=10, verbose_name='Unidade')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('avg_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Custo Médio')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
                'unique_together': {('tenant', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU Variação')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome da Variação')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('avg_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Custo Médio')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'VARIABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produtos',
                'ordering': ['product', 'name'],
                'unique_together': {('tenant', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.attributetype', verbose_name='Tipo de Atributo')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
                'ordering': ['attribute_type__name'],
                'unique_together': {('variant', 'attribute_type')},
            },
        ),
    ]
