# Generated by Django 5.2.10 on 2026-01-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_location'),
        ('partners', '0002_rename_partners_supplier_cnpj_idx_partners_su_tenant__fdc31d_idx_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='inventory.location', verbose_name='Local de Estoque Padrão'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='partners.supplier', verbose_name='Fornecedor Padrão'),
        ),
    ]
