# Generated by Django 5.2.10 on 2026-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tracks_expiry",
            field=models.BooleanField(
                default=False,
                help_text="Registra lote e data de validade nas entradas; saídas consomem primeiro o que vence antes (FEFO).",
                verbose_name="Controla validade",
            ),
        ),
    ]
