# Generated by Django 5.2.10 on 2026-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_default_location_product_default_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU Variação'),
        ),
    ]
