# Generated by Django 5.2.10 on 2026-01-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='current_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Estoque Mínimo'),
        ),
    ]
