# Generated by Django 5.2.10 on 2026-01-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_confidence',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Confiança IA'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_review',
            field=models.BooleanField(default=False, verbose_name='Requer Revisão'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='ai_confidence',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Confiança IA'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='requires_review',
            field=models.BooleanField(default=False, verbose_name='Requer Revisão'),
        ),
    ]
