# Generated by Django 5.2.10 on 2026-02-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_external_id_product_external_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="avg_unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Custo Médio (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Código de Barras (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Estoque Atual (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=12,
                verbose_name="Estoque Mínimo (Legado)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
    ]
