# Generated by Django 5.2.10 on 2026-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_data_migrate_to_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                default="TEMP", max_length=50, verbose_name="SKU Variação"
            ),
        ),
    ]
