# Generated by Django 5.2.10 on 2026-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productvariant_sku"),
        ("tenants", "0003_alter_plan_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(max_length=50, verbose_name="SKU Variação"),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sku"), name="unique_sku_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", 0)), name="stock_non_negative"
            ),
        ),
    ]
