# Generated by Django 5.2.10 on 2026-02-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_importbatch_type_alter_stockmovement_variant"),
        (
            "partners",
            "0002_rename_partners_supplier_cnpj_idx_partners_su_tenant__fdc31d_idx_and_more",
        ),
        ("products", "0010_alter_productvariant_unique_together_and_more"),
        ("tenants", "0003_alter_plan_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sku"), name="unique_product_sku_per_tenant"
            ),
        ),
    ]
