# Generated by Django 5.2.10 on 2026-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("OK", "OK"),
                    ("DIVERGENT", "Divergente"),
                    ("RECONCILED", "Reconciliado"),
                ],
                default="OK",
                max_length=20,
                verbose_name="Status de Inventário",
            ),
        ),
    ]
