# Generated by Django 5.2.10 on 2026-02-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_sale_price_productvariant_sale_price"),
        ("products", "0014_merge_sale_price"),
    ]

    operations = []
