# Generated by Django 5.2.10 on 2026-02-18 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        ("products", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproductmap",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_mappings",
                to="products.product",
                verbose_name="Produto",
            ),
        ),
        migrations.AddField(
            model_name="supplierproductmap",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_mappings",
                to="partners.supplier",
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="supplierproductmap",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="supplierproductmap",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_mappings",
                to="products.productvariant",
                verbose_name="Variação",
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["tenant", "cnpj"], name="partners_su_tenant__fdc31d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["tenant", "is_active"], name="partners_su_tenant__5d0f53_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("tenant", "cnpj")},
        ),
        migrations.AddIndex(
            model_name="supplierproductmap",
            index=models.Index(
                fields=["tenant", "supplier", "supplier_sku"],
                name="partners_su_tenant__a7bde1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproductmap",
            index=models.Index(
                fields=["tenant", "supplier_ean"], name="partners_su_tenant__e4ceb6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplierproductmap",
            unique_together={("tenant", "supplier", "supplier_sku")},
        ),
    ]
