# Generated by Django 5.2.10 on 2026-01-16 21:47

from django.db import migrations, models

import apps.partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supplier',
            new_name='partners_su_tenant__fdc31d_idx',
            old_name='partners_supplier_cnpj_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='partners_su_tenant__5d0f53_idx',
            old_name='partners_supplier_active_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierproductmap',
            new_name='partners_su_tenant__a7bde1_idx',
            old_name='partners_map_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierproductmap',
            new_name='partners_su_tenant__e4ceb6_idx',
            old_name='partners_map_ean_idx',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(help_text='CNPJ do fornecedor (com ou sem formatação)', max_length=18, validators=[apps.partners.models.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
