# Generated by Django 5.2.10 on 2026-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproductmap",
            name="conversion_factor",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Unidades do estoque por unidade da nota (ex.: caixa com 12 = 12)",
                max_digits=12,
                verbose_name="Fator de conversão",
            ),
        ),
    ]

