# Generated by Django 5.2.10 on 2026-01-16 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário (DEPRECATED)', 'verbose_name_plural': 'Perfis de Usuário (DEPRECATED)'},
        ),
        migrations.CreateModel(
            name='TenantInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Convidado')),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('OPERATOR', 'Operador')], default='OPERATOR', max_length=20)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('ADMIN', 'Administrador'), ('OPERATOR', 'Operador')], default='OPERATOR', max_length=20, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Empresa',
                'verbose_name_plural': 'Membros das Empresas',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
