version: "3.8"

services:

  migrate:
    image: brunobh51/stockpro:v10
    # COMANDO LIMPO: Executa migrações, estáticos e o seed_db que criamos acima
    command: >
      sh -c "python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python manage.py seed_db"
    environment:
      TZ: America/Sao_Paulo
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      # ATENÇÃO: Verifique o DB_HOST no seu .env (não use localhost)
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - app_network
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  stockpro:
    image: brunobh51/stockpro:v10
    environment:
      TZ: America/Sao_Paulo
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      ADMIN_URL: ${ADMIN_URL}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      XAI_API_KEY: ${XAI_API_KEY}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - imports_volume:/app/imports
    networks:
      - traefik_public
      - app_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.http.routers.stockpro.rule=Host(`stockpro.lojabibelo.com.br`)
        - traefik.http.routers.stockpro.entrypoints=websecure
        - traefik.http.routers.stockpro.tls.certresolver=le
        - traefik.http.services.stockpro.loadbalancer.server.port=8000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  worker:
    image: brunobh51/stockpro:v10
    command: celery -A stock_control worker -l info --concurrency=2
    environment:
      TZ: America/Sao_Paulo
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      XAI_API_KEY: ${XAI_API_KEY}
    networks:
      - app_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "celery -A stock_control inspect ping"]
      interval: 60s
      timeout: 10s
      retries: 3

  beat:
    image: brunobh51/stockpro:v10
    command: celery -A stock_control beat -l info --schedule=/app/celerybeat-schedule
    environment:
      TZ: America/Sao_Paulo
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    networks:
      - app_network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "celery -A stock_control inspect ping"]
      interval: 60s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  static_volume:
  media_volume:
  imports_volume:
  redis_data:
  celerybeat_data:

networks:
  traefik_public:
    external: true
  app_network:
    external: true
