version: "3.8"

# ===========================================
# StockPro - Stack PostgreSQL (Separada)
# ===========================================
# Deploy: docker stack deploy -c docker-stack-db.yml stockpro_db
# ===========================================

services:
  postgres:
    image: postgres:15-alpine
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: ${DB_NAME:-stockpro_db}
      POSTGRES_USER: ${DB_USER:-stockpro_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Performance tuning para Oracle Free Tier (1GB RAM)
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=pt_BR.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backup
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-stockpro_user} -d ${DB_NAME:-stockpro_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Serviço de backup automático (opcional)
  pgbackup:
    image: postgres:15-alpine
    environment:
      TZ: America/Sao_Paulo
      PGHOST: postgres
      PGUSER: ${DB_USER:-stockpro_user}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: ${DB_NAME:-stockpro_db}
    volumes:
      - postgres_backup:/backup
    networks:
      - app_network
    entrypoint: /bin/sh
    command: >
      -c 'while true; do
        echo "[$(date)] Iniciando backup...";
        pg_dump -Fc > /backup/stockpro_$$(date +%Y%m%d_%H%M%S).dump;
        echo "[$(date)] Backup concluído";
        find /backup -name "*.dump" -mtime +7 -delete;
        echo "[$(date)] Backups antigos removidos. Próximo em 24h";
        sleep 86400;
      done'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

volumes:
  postgres_data:
    driver: local
  postgres_backup:
    driver: local

networks:
  app_network:
    external: true
