# StockPro - Local Test Docker Compose

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=stockpro_db
      - POSTGRES_USER=stockpro_user
      - POSTGRES_PASSWORD=StockPro@2026!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stockpro_user -d stockpro_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python manage.py seed_db"
    environment:
      - DEBUG=True
      - SECRET_KEY=test-secret-key
      - DB_HOST=db
      - DB_NAME=stockpro_db
      - DB_USER=stockpro_user
      - DB_PASSWORD=StockPro@2026!
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
      - imports_data:/app/imports
    environment:
      - DEBUG=True
      - SECRET_KEY=test-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DB_HOST=db
      - DB_NAME=stockpro_db
      - DB_USER=stockpro_user
      - DB_PASSWORD=StockPro@2026!
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  worker:
    build: .
    command: celery -A stock_control worker -l info
    volumes:
      - media_data:/app/media
      - imports_data:/app/imports
    environment:
      - DEBUG=True
      - SECRET_KEY=test-secret-key
      - DB_HOST=db
      - DB_NAME=stockpro_db
      - DB_USER=stockpro_user
      - DB_PASSWORD=StockPro@2026!
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  beat:
    build: .
    command: celery -A stock_control beat -l info --schedule=/app/celerybeat-schedule
    environment:
      - DEBUG=True
      - SECRET_KEY=test-secret-key
      - DB_HOST=db
      - DB_NAME=stockpro_db
      - DB_USER=stockpro_user
      - DB_PASSWORD=StockPro@2026!
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  media_data:
  imports_data:
