# Generated by Django 5.2.10 on 2026-01-16 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Marca')),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa/Unidade')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('subdomain', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant (Empresa)',
                'verbose_name_plural': 'Tenants (Empresas)',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit - Código único do produto', max_length=50)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('uom', models.CharField(help_text='Ex: UN, KG, LT', max_length=20, verbose_name='Unidade de Medida')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('current_stock', models.IntegerField(default=0, editable=False, verbose_name='Estoque Atual')),
                ('avg_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Médio Unitário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='Categoria')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports/%Y/%m/%d/', verbose_name='Arquivo')),
                ('type', models.CharField(choices=[('CSV_PRODUCTS', 'Importar Produtos (CSV)'), ('XML_NFE', 'Nota Fiscal Eletrônica (XML)')], max_length=20, verbose_name='Tipo de Importação')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('ERROR', 'Erro')], default='PENDING', max_length=20)),
                ('log', models.TextField(blank=True, verbose_name='Log de Processamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Lote de Importação',
                'verbose_name_plural': 'Lotes de Importação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='StockPro Enterprise', max_length=100, verbose_name='Nome da Empresa')),
                ('company_logo_url', models.URLField(blank=True, null=True, verbose_name='URL do Logotipo')),
                ('prevent_negative_stock', models.BooleanField(default=True, help_text='Bloqueia saídas se não houver saldo suficiente.', verbose_name='Impedir Estoque Negativo')),
                ('low_stock_threshold_global', models.PositiveIntegerField(default=5, verbose_name='Alerta Global de Estoque Baixo')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Habilitar Notificações')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'unique_together': {('tenant',)},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('ADJUSTMENT', 'Ajuste de Inventário')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('balance_before', models.IntegerField(editable=False, verbose_name='Saldo Anterior')),
                ('balance_after', models.IntegerField(editable=False, verbose_name='Saldo Posterior')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo/Justificativa')),
                ('source', models.CharField(blank=True, help_text='Origem: MANUAL, API, XML, CSV', max_length=100, null=True)),
                ('source_doc', models.CharField(blank=True, help_text='Ex: NF-e 1234, Pedido Importação #99', max_length=100, null=True, verbose_name='Documento de Origem')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Unitário (Entrada)')),
                ('batch_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote / Validade')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref. Externa')),
                ('idempotency_key', models.UUIDField(blank=True, help_text='Chave para prevenir duplicação de requisições', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.product', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_stockm_created_a48320_idx'), models.Index(fields=['type'], name='core_stockm_type_ea40d5_idx'), models.Index(fields=['source'], name='core_stockm_source_cf1ad8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='core_produc_name_be3252_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='core_produc_categor_784c92_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='core_produc_brand_i_be2a48_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='core_produc_is_acti_1d1aa8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('tenant', 'name')},
        ),
    ]
