# Generated by Django 5.2.10 on 2026-01-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_tenant_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cnpj',
            field=models.CharField(blank=True, help_text='XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
