# Generated by Django 5.2.10 on 2026-01-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Em Teste'), ('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CANCELLED', 'Cancelado')], default='TRIAL', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Período de Teste'),
        ),
    ]
