# Generated by Django 5.2.10 on 2026-02-18 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(db_index=True, max_length=50)),
                ("provider", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
                ("prompt_text", models.TextField()),
                ("response_json", models.JSONField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Decisão IA",
                "verbose_name_plural": "Logs de Decisão IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Minha Empresa", max_length=100),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                (
                    "alert_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("low_stock_alert_threshold", models.PositiveIntegerField(default=10)),
                ("enable_auto_cost_update", models.BooleanField(default=True)),
                (
                    "ai_import_mode",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("HYBRID", "Híbrido"),
                            ("AUTO", "Automático"),
                        ],
                        default="HYBRID",
                        max_length=10,
                    ),
                ),
                (
                    "ai_auto_approve_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.9,
                        max_digits=3,
                        verbose_name="Limiar de Auto-Aprovação AI",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração Global",
                "verbose_name_plural": "Configurações Globais",
            },
        ),
        migrations.CreateModel(
            name="VisualAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=20)),
                ("source", models.CharField(max_length=50)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("diff", models.JSONField(blank=True, null=True)),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria Visual",
                "verbose_name_plural": "Auditorias Visuais",
                "ordering": ["-created_at"],
            },
        ),
    ]
