# Generated by Django 5.2.10 on 2026-01-16 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Minha Empresa', max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('alert_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('low_stock_alert_threshold', models.PositiveIntegerField(default=10)),
                ('enable_auto_cost_update', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
    ]
