# Generated by Django 5.2.10 on 2026-01-17 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenants', '0003_alter_plan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='ai_auto_approve_threshold',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=3, verbose_name='Limiar de Auto-Aprovação AI'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='ai_import_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('HYBRID', 'Híbrido'), ('AUTO', 'Automático')], default='HYBRID', max_length=10),
        ),
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('prompt_text', models.TextField()),
                ('response_json', models.JSONField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Decisão IA',
                'verbose_name_plural': 'Logs de Decisão IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
