# Generated by Django 5.2.10 on 2026-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="expiry_alert_days",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Avisar validade com antecedência (dias)"
            ),
        ),
    ]
