# Generated by Django 5.2.10 on 2026-10-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_validade_lotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="low_stock_alerted_ids",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="low_stock_alerts_enabled",
            field=models.BooleanField(
                default=False,
                verbose_name="Avisar quando produtos chegarem ao estoque mínimo",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="weekly_summary_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Resumo semanal na segunda de manhã"
            ),
        ),
    ]
