# Generated by Django 5.2.10 on 2026-01-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=50, unique=True)),
                ('display_name', models.CharField(default='Plano', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_products', models.PositiveIntegerField(default=50, help_text='Limite de produtos cadastrados')),
                ('max_users', models.PositiveIntegerField(default=3, help_text='Limite de usuários na empresa')),
                ('features', models.TextField(blank=True, help_text='Lista de features separadas por vírgula')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa/Unidade')),
                ('cnpj', models.CharField(blank=True, help_text='XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('subdomain', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'Em Teste'), ('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CANCELLED', 'Cancelado')], default='TRIAL', max_length=20, verbose_name='Status da Assinatura')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Período de Teste')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.plan')),
            ],
            options={
                'verbose_name': 'Tenant (Empresa)',
                'verbose_name_plural': 'Tenants (Empresas)',
            },
        ),
    ]
