# Generated by Django 5.2.10 on 2026-01-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_ai_matching',
            field=models.BooleanField(default=False, help_text='Habilita match inteligente de produtos via IA'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_ai_reconciliation',
            field=models.BooleanField(default=False, help_text='Habilita conciliação automática via IA'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('GRATUITO', 'Gratuito'), ('INICIAL', 'Inicial'), ('PROFISSIONAL', 'Profissional'), ('CORPORATIVO', 'Corporativo')], max_length=50, unique=True),
        ),
    ]
