# Generated by Django 5.2.10 on 2026-01-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plan_has_ai_matching_plan_has_ai_reconciliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Identificador do Plano'),
        ),
    ]
