# Generated by Django 5.2.10 on 2026-10-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_enterprise_price_697"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("trigger", models.CharField(default="beat", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Em andamento"),
                            ("SUCCESS", "Concluído"),
                            ("LOCAL_ONLY", "Concluído só no servidor"),
                            ("FAILED", "Falhou"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("db_size_bytes", models.BigIntegerField(default=0)),
                ("media_size_bytes", models.BigIntegerField(default=0)),
                ("encrypted", models.BooleanField(default=False)),
                ("remote_keys", models.JSONField(blank=True, default=list)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Execução de backup",
                "verbose_name_plural": "Execuções de backup",
                "ordering": ["-started_at"],
            },
        ),
    ]

