# Generated by Django 5.2.10 on 2026-10-09 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_backup_run"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="next_due_date",
            field=models.DateField(
                blank=True,
                help_text="Controle manual de cobrança (enquanto não há gateway de pagamento).",
                null=True,
                verbose_name="Próximo vencimento",
            ),
        ),
        migrations.CreateModel(
            name="TenantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CREATED", "Cadastro"),
                            ("PLAN", "Troca de plano"),
                            ("STATUS", "Mudança de status"),
                            ("TRIAL", "Período de teste"),
                            ("DUE_DATE", "Vencimento"),
                            ("NOTE", "Nota interna"),
                            ("SECURITY", "Segurança"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio = sistema (tarefa automática)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da empresa",
                "verbose_name_plural": "Histórico das empresas",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
