# Generated by Django 5.2.10 on 2026-10-10 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0006_central_plataforma"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "width_mm",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Largura da etiqueta (mm)",
                    ),
                ),
                (
                    "height_mm",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Altura da etiqueta (mm)",
                    ),
                ),
                (
                    "columns",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Etiquetas por linha (colunas)",
                    ),
                ),
                (
                    "column_gap_mm",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Espaço entre colunas (mm)",
                    ),
                ),
                (
                    "dpi",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (203, "203 dpi (8 pontos/mm), ex.: ZD220, ZD230, GC420"),
                            (300, "300 dpi (12 pontos/mm), ex.: ZD421 300, ZT230 300"),
                        ],
                        default=203,
                        verbose_name="Resolução da impressora",
                    ),
                ),
                (
                    "darkness",
                    models.SmallIntegerField(
                        default=0,
                        help_text="0 mantém o da impressora. Aumente se as barras saírem falhadas.",
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Ajuste de escuridão",
                    ),
                ),
                (
                    "print_speed",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Padrão da impressora"),
                            (2, "2 pol/s (mais nítido)"),
                            (3, "3 pol/s"),
                            (4, "4 pol/s"),
                            (5, "5 pol/s"),
                            (6, "6 pol/s (mais rápido)"),
                        ],
                        default=0,
                        verbose_name="Velocidade",
                    ),
                ),
                (
                    "offset_x_mm",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Positivo empurra para a direita.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Ajuste horizontal (mm)",
                    ),
                ),
                (
                    "offset_y_mm",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Positivo empurra para baixo (até 10 mm a 300 dpi, 15 mm a 203 dpi).",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Ajuste vertical (mm)",
                    ),
                ),
                (
                    "show_store",
                    models.BooleanField(default=True, verbose_name="Nome da loja"),
                ),
                (
                    "store_text",
                    models.CharField(
                        blank=True,
                        help_text="Vazio usa o nome da empresa das Configurações.",
                        max_length=40,
                        verbose_name="Texto da loja",
                    ),
                ),
                (
                    "show_name",
                    models.BooleanField(default=True, verbose_name="Nome do produto"),
                ),
                (
                    "show_variant",
                    models.BooleanField(
                        default=True, verbose_name="Variação (cor, tamanho)"
                    ),
                ),
                (
                    "show_price",
                    models.BooleanField(default=True, verbose_name="Preço de venda"),
                ),
                ("show_sku", models.BooleanField(default=True, verbose_name="SKU")),
                (
                    "show_barcode",
                    models.BooleanField(default=True, verbose_name="Código de barras"),
                ),
                (
                    "code_source",
                    models.CharField(
                        choices=[
                            ("auto", "EAN do cadastro; sem EAN, o SKU"),
                            ("sku", "Sempre o SKU"),
                        ],
                        default="auto",
                        max_length=10,
                        verbose_name="O que vai no código de barras",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de etiqueta",
                "verbose_name_plural": "Configurações de etiqueta",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="unique_label_settings_per_tenant"
                    )
                ],
            },
        ),
    ]
