# Generated by Django 5.2.10 on 2026-10-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("products", "0002_validade_lotes"),
        ("tenants", "0006_central_plataforma"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labelsettings",
            name="code_label",
            field=models.CharField(
                blank=True,
                default="CÓDIGO:",
                help_text='No estilo "código + nome". Ex.: CÓDIGO: 139557. Vazio imprime só o código.',
                max_length=20,
                verbose_name="Texto antes do código",
            ),
        ),
        migrations.AddField(
            model_name="labelsettings",
            name="layout",
            field=models.CharField(
                choices=[
                    ("complete", "Completa: loja, nome, variação, preço e código"),
                    (
                        "code_name",
                        "Código + nome + código de barras (etiqueta pequena)",
                    ),
                ],
                default="complete",
                max_length=12,
                verbose_name="Estilo da etiqueta",
            ),
        ),
        migrations.CreateModel(
            name="VariantLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Nome na etiqueta"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Código impresso"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_text",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Texto de etiqueta",
                "verbose_name_plural": "Textos de etiqueta",
            },
        ),
    ]
