# Generated by Django 5.2.10 on 2026-02-18 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_type", models.CharField(max_length=30)),
                ("pattern_value", models.CharField(max_length=255)),
                ("confidence_score", models.FloatField(default=0.5)),
                ("times_confirmed", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de Importação",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="DRAFT", max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryAuditItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ledger_quantity",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "physical_quantity",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "adjustment_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex: LOJ-001", max_length=20, verbose_name="Código"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("STORE", "Loja"),
                            ("WAREHOUSE", "Depósito"),
                            ("SHELF", "Prateleira"),
                            ("DISPLAY", "Expositor"),
                            ("TRANSIT", "Em Trânsito"),
                            ("QUARANTINE", "Quarentena"),
                        ],
                        default="STORE",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Local padrão para recebimento"
                    ),
                ),
                ("allows_negative", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Saída"),
                            ("ADJ", "Ajuste"),
                        ],
                        max_length=3,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, default="MANUAL", max_length=50),
                ),
                ("source_doc", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PROCESSING", "Processando"),
                            ("COMPLETED", "Concluído"),
                            ("FAILED", "Falha"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("EXCEL", "Excel"), ("JSON", "JSON")],
                        default="CSV",
                        max_length=10,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("PRODUCTS", "Produtos"),
                            ("MOVEMENTS", "Movimentações"),
                        ],
                        default="PRODUCTS",
                        max_length=20,
                    ),
                ),
                (
                    "params",
                    models.TextField(
                        blank=True,
                        default="{}",
                        help_text="JSON params for export filtering",
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("log", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Exportação",
                "verbose_name_plural": "Lotes de Exportação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("external_order_id", models.CharField(db_index=True, max_length=100)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido Externo",
                "verbose_name_plural": "Pedidos Externos",
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "CATALOG_DIRECT",
                                "Criação/Update de Catálogo (Completo/CSV)",
                            ),
                            ("STOCK_SYNC", "Sincronização de Estoque (SKU Only/CSV)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="imports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PROCESSING", "Processando"),
                            ("PENDING_REVIEW", "Aguardando Revisão"),
                            ("COMPLETED", "Concluído"),
                            ("FAILED", "Falha"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("log", models.TextField(blank=True, null=True)),
                ("source_doc", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Importação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CSV", "Importação CSV"),
                            ("API", "Integração API"),
                            ("MANUAL", "Manual"),
                        ],
                        default="CSV",
                        max_length=20,
                    ),
                ),
                ("supplier_sku", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField()),
                ("ean", models.CharField(blank=True, max_length=20, null=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=12)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Aguardando Revisão"),
                            ("PROCESSING", "Em Processamento"),
                            ("DONE", "Processado"),
                            ("REJECTED", "Rejeitado"),
                            ("ERROR", "Erro"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("ai_suggestion", models.JSONField(blank=True, null=True)),
                (
                    "ai_confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("ai_logic_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-ai_confidence"],
            },
        ),
    ]
