# Generated by Django 5.2.10 on 2026-01-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_v2_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='location',
            new_name='inventory_l_tenant__ddf11d_idx',
            old_name='inv_loc_tenant_code_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='inventory_l_tenant__9cc6fd_idx',
            old_name='inv_loc_tenant_active_idx',
        ),
    ]
