# Generated by Django 5.2.10 on 2026-10-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("products", "0002_validade_lotes"),
        ("tenants", "0004_enterprise_price_697"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="Lote"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Validade"
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(blank=True, null=True, verbose_name="Fabricação"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo do lote",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="products.productvariant",
                        verbose_name="Variação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": [
                    models.OrderBy(models.F("expiry_date"), nulls_last=True),
                    "created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="MovementLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_allocations",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="inventory.stocklot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote da movimentação",
                "verbose_name_plural": "Lotes das movimentações",
            },
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="lot_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.UniqueConstraint(
                fields=("variant", "lot_number", "expiry_date"),
                name="unique_lot_per_variant_expiry",
            ),
        ),
    ]
