# Generated by Django 5.2.10 on 2026-01-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inv_loc_tenant_code_idx_inventory_l_tenant__ddf11d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.location', verbose_name='Local de Estoque'),
        ),
    ]
