# Generated by Django 5.2.10 on 2026-10-09 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_validade_lotes"),
        ("partners", "0003_nfe_entrada"),
        ("products", "0002_validade_lotes"),
        ("tenants", "0005_backup_run"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NfeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_key",
                    models.CharField(max_length=44, verbose_name="Chave de acesso"),
                ),
                ("number", models.CharField(blank=True, max_length=20)),
                ("series", models.CharField(blank=True, max_length=5)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("supplier_cnpj", models.CharField(blank=True, max_length=14)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("supplier_trade_name", models.CharField(blank=True, max_length=200)),
                ("supplier_ie", models.CharField(blank=True, max_length=20)),
                ("supplier_city", models.CharField(blank=True, max_length=100)),
                ("supplier_state", models.CharField(blank=True, max_length=2)),
                ("recipient_cnpj", models.CharField(blank=True, max_length=14)),
                (
                    "total_products",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_invoice",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "authorized",
                    models.BooleanField(
                        default=False, verbose_name="Tem protocolo de autorização"
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("xml_file", models.FileField(upload_to="nfe/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Em revisão"),
                            ("IMPORTED", "Importada"),
                            ("REVERTED", "Desfeita"),
                            ("DISCARDED", "Descartada"),
                        ],
                        default="PREVIEW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "NF-e de entrada",
                "verbose_name_plural": "NF-e de entrada",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NfeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.PositiveIntegerField()),
                ("supplier_code", models.CharField(blank=True, max_length=60)),
                ("ean", models.CharField(blank=True, max_length=14)),
                ("description", models.CharField(max_length=255)),
                ("ncm", models.CharField(blank=True, max_length=10)),
                ("cfop", models.CharField(blank=True, max_length=4)),
                ("unit", models.CharField(blank=True, max_length=10)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=10, default=0, max_digits=21),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "freight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "insurance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "other",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "ipi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "icms_st",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("lots", models.JSONField(blank=True, default=list)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("LINK", "Vincular a produto existente"),
                            ("CREATE", "Criar produto novo"),
                            ("IGNORE", "Ignorar (não dar entrada)"),
                            ("PENDING", "Decidir"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("match_source", models.CharField(blank=True, max_length=20)),
                (
                    "conversion_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12),
                ),
                ("factor_suggested", models.BooleanField(default=False)),
                ("new_product_name", models.CharField(blank=True, max_length=255)),
                ("movement_ids", models.JSONField(blank=True, default=list)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.nfedocument",
                    ),
                ),
                (
                    "new_product_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["item_number"],
            },
        ),
        migrations.CreateModel(
            name="NfeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_include_ipi",
                    models.BooleanField(
                        default=True, verbose_name="Somar IPI ao custo"
                    ),
                ),
                (
                    "cost_include_st",
                    models.BooleanField(
                        default=True, verbose_name="Somar ICMS-ST (e FCP-ST) ao custo"
                    ),
                ),
                (
                    "cost_include_freight",
                    models.BooleanField(
                        default=True, verbose_name="Somar frete ao custo"
                    ),
                ),
                (
                    "cost_include_insurance",
                    models.BooleanField(
                        default=True, verbose_name="Somar seguro ao custo"
                    ),
                ),
                (
                    "cost_include_other",
                    models.BooleanField(
                        default=True, verbose_name="Somar outras despesas ao custo"
                    ),
                ),
                (
                    "cost_subtract_discount",
                    models.BooleanField(
                        default=True, verbose_name="Descontar o desconto do custo"
                    ),
                ),
                (
                    "match_supplier_code",
                    models.BooleanField(
                        default=True,
                        verbose_name="Pelo código do fornecedor já aprendido",
                    ),
                ),
                (
                    "match_ean",
                    models.BooleanField(
                        default=True, verbose_name="Pelo código de barras (EAN)"
                    ),
                ),
                (
                    "match_sku",
                    models.BooleanField(
                        default=False,
                        verbose_name="Pelo SKU igual ao código do fornecedor",
                    ),
                ),
                (
                    "new_product_policy",
                    models.CharField(
                        choices=[
                            ("REVIEW", "Decidir item a item na prévia (padrão)"),
                            (
                                "AUTO_CREATE",
                                'Sugerir "criar produto novo" para itens não encontrados',
                            ),
                        ],
                        default="REVIEW",
                        max_length=20,
                        verbose_name="Itens não encontrados",
                    ),
                ),
                (
                    "sku_policy",
                    models.CharField(
                        choices=[
                            ("AUTO", "Gerar SKU automaticamente"),
                            ("SUPPLIER_CODE", "Usar o código do fornecedor (cProd)"),
                            ("EAN", "Usar o EAN, quando houver"),
                        ],
                        default="AUTO",
                        max_length=20,
                        verbose_name="SKU dos produtos criados pela nota",
                    ),
                ),
                (
                    "title_case_names",
                    models.BooleanField(
                        default=True,
                        verbose_name="Ajustar nomes em MAIÚSCULAS (Caneta Azul)",
                    ),
                ),
                (
                    "auto_tracks_expiry",
                    models.BooleanField(
                        default=True,
                        verbose_name="Ligar 'controla validade' quando a nota trouxer lote",
                    ),
                ),
                (
                    "require_recipient_cnpj",
                    models.BooleanField(
                        default=True,
                        verbose_name="Exigir confirmação quando o destinatário não for o CNPJ da empresa",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                        verbose_name="Categoria padrão dos produtos novos",
                    ),
                ),
                (
                    "default_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.location",
                        verbose_name="Local de entrada padrão",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de NF-e",
            },
        ),
        migrations.AddConstraint(
            model_name="nfedocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PREVIEW", "IMPORTED"])),
                fields=("tenant", "access_key"),
                name="unique_active_nfe_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="nfesettings",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="unique_nfe_settings_per_tenant"
            ),
        ),
    ]

