# Generated by Django 5.2.10 on 2026-01-17 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_location'),
        ('tenants', '0002_plan_has_ai_matching_plan_has_ai_reconciliation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='source_doc',
            field=models.CharField(blank=True, help_text='Identificador único (ex: NFE-CNPJ-SERIE-NUMERO)', max_length=100, null=True, verbose_name='Documento de Origem'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['tenant', 'source_doc'], name='inventory_i_tenant__747d4b_idx'),
        ),
    ]
