# Generated by Django 5.2.10 on 2026-01-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_source_doc_to_importbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='type',
            field=models.CharField(choices=[('CSV_PRODUCTS', 'CSV de Produtos (Soma)'), ('CSV_VARIANTS', 'CSV de Variações (Soma)'), ('CSV_INVENTORY', 'CSV de Inventário (Sobrescreve)'), ('XML_NFE', 'XML de NF-e')], max_length=20),
        ),
    ]
