# Generated by Django 5.2.10 on 2026-01-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_importbatch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='balance_after',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Saldo Após'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade'),
        ),
    ]
