# Generated by Django 5.2.10 on 2026-01-17 20:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockmovement_balance_after_and_more'),
        ('products', '0004_alter_product_current_stock_and_more'),
        ('tenants', '0003_alter_plan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('COMPLETED', 'Concluído/Reconciliado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='inventory.location', verbose_name='Local Auditado')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de Estoque',
                'verbose_name_plural': 'Auditorias de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qtd no Sistema')),
                ('physical_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qtd Física')),
                ('adjustment_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Ajuste')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryaudit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'unique_together': {('audit', 'product', 'variant')},
            },
        ),
    ]
