# Generated by Django 5.2.10 on 2026-01-17 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryaudit_inventoryaudititem'),
        ('products', '0004_alter_product_current_stock_and_more'),
        ('tenants', '0003_alter_plan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='importbatch',
            old_name='log',
            new_name='error_log',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='file',
            field=models.FileField(upload_to='imports/'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('PENDING_REVIEW', 'Aguardando Revisão'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falha')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(verbose_name='Dados Originais')),
                ('suggested_data', models.JSONField(verbose_name='Sugestão da IA')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ai_logic_summary', models.TextField(blank=True, verbose_name='Raciocínio da IA')),
                ('matching_strategy', models.CharField(blank=True, max_length=50)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_products', to='inventory.importbatch')),
                ('parent_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Produto em Revisão',
                'verbose_name_plural': 'Produtos em Revisão',
                'ordering': ['-confidence_score'],
            },
        ),
    ]
