# Generated by Django 5.2.10 on 2026-01-17 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_log_importbatch_error_log_and_more'),
        ('partners', '0002_rename_partners_supplier_cnpj_idx_partners_su_tenant__fdc31d_idx_and_more'),
        ('products', '0004_alter_product_current_stock_and_more'),
        ('tenants', '0003_alter_plan_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingproduct',
            options={'verbose_name': 'Produto em Revisão (V20)', 'verbose_name_plural': 'Produtos em Revisão (V20)'},
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('ean', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Revisão'), ('PROCESSING', 'Em Processamento'), ('DONE', 'Processado com Sucesso'), ('REJECTED', 'Rejeitado pelo Usuário'), ('ERROR', 'Erro no Processamento')], default='PENDING', max_length=20)),
                ('ai_suggestion', models.JSONField(blank=True, null=True)),
                ('ai_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('ai_logic_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.importbatch')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('matched_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Item de Importação',
                'verbose_name_plural': 'Itens de Importação',
                'ordering': ['-ai_confidence'],
            },
        ),
        migrations.CreateModel(
            name='ImportKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('VARIANT_INDICATOR', 'Indicador de Variação'), ('PRODUCT_GROUP', 'Agrupamento de Produto'), ('IGNORE_TOKEN', 'Token para Ignorar'), ('SKU_PATTERN', 'Padrão de SKU')], max_length=30)),
                ('pattern_value', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('times_confirmed', models.PositiveIntegerField(default=0)),
                ('times_rejected', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.attributetype')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Conhecimento de Importação',
                'verbose_name_plural': 'Conhecimentos de Importação',
                'unique_together': {('tenant', 'pattern_type', 'pattern_value', 'supplier')},
            },
        ),
    ]
