# Generated by Django 5.2.10 on 2026-01-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_pendingproduct_options_importitem_and_more'),
        ('partners', '0002_rename_partners_supplier_cnpj_idx_partners_su_tenant__fdc31d_idx_and_more'),
        ('products', '0005_add_ai_hardening_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingproduct',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='pendingproduct',
            name='parent_product',
        ),
        migrations.RemoveField(
            model_name='pendingproduct',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='pendingproduct',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='adjustmentreason',
            options={},
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lote de Importação'},
        ),
        migrations.AlterModelOptions(
            name='importitem',
            options={'ordering': ['-ai_confidence']},
        ),
        migrations.AlterModelOptions(
            name='importknowledge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ['row_number'], 'verbose_name': 'Log de Importação'},
        ),
        migrations.AlterModelOptions(
            name='inventoryaudit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pendingassociation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='importbatch',
            name='inventory_i_tenant__747d4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_l_tenant__ddf11d_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='inventory_l_tenant__9cc6fd_idx',
        ),
        migrations.RenameField(
            model_name='importbatch',
            old_name='error_log',
            new_name='log',
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentreason',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='importknowledge',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='importlog',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryaudititem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pendingassociation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventoryaudit',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='inventoryaudit',
            name='notes',
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='impact_type',
            field=models.CharField(default='NEUTRAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='requires_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source_doc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='type',
            field=models.CharField(choices=[('CSV_PRODUCTS', 'CSV de Produtos'), ('CSV_VARIANTS', 'CSV de Variações'), ('CSV_INVENTORY', 'CSV de Inventário'), ('XML_NFE', 'XML de NF-e')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Revisão'), ('PROCESSING', 'Em Processamento'), ('DONE', 'Processado'), ('REJECTED', 'Rejeitado'), ('ERROR', 'Erro')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='importknowledge',
            name='pattern_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_legacy', to='inventory.importbatch'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='row_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='status',
            field=models.CharField(default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='inventoryaudititem',
            name='adjustment_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryaudititem',
            name='ledger_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryaudititem',
            name='physical_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='allows_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(help_text='Ex: LOJ-001', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Local padrão para recebimento'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('STORE', 'Loja'), ('WAREHOUSE', 'Depósito'), ('SHELF', 'Prateleira'), ('DISPLAY', 'Expositor'), ('TRANSIT', 'Em Trânsito'), ('QUARANTINE', 'Quarentena')], default='STORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.importbatch'),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='match_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='ncm',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='nfe_key',
            field=models.CharField(blank=True, max_length=44),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='nfe_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='resolved_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='resolved_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.supplier'),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='supplier_ean',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='supplier_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='supplier_sku',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingassociation',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='balance_after',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.productvariant'),
        ),
        migrations.DeleteModel(
            name='PendingProduct',
        ),
        migrations.RemoveField(
            model_name='adjustmentreason',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adjustmentreason',
            name='description',
        ),
        migrations.RemoveField(
            model_name='importknowledge',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='importknowledge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='importknowledge',
            name='times_rejected',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pendingassociation',
            name='resolved_by',
        ),
    ]
