# Generated by Django 5.2.10 on 2026-01-23 18:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_pendingproduct_batch_and_more'),
        ('tenants', '0003_alter_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('external_order_id', models.CharField(db_index=True, max_length=100)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pedido Externo',
                'verbose_name_plural': 'Pedidos Externos',
                'unique_together': {('tenant', 'platform', 'external_order_id')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='external_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.externalorder'),
        ),
    ]
