# Generated by Django 5.2.10 on 2026-01-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_externalorder_stockmovement_external_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='importitem',
            name='source',
            field=models.CharField(choices=[('XML', 'Importação XML'), ('CSV', 'Importação CSV'), ('API', 'Integração API'), ('MANUAL', 'Manual')], default='XML', max_length=20),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.importbatch'),
        ),
    ]
