# Generated by Django 5.2.10 on 2026-02-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_importitem_source_alter_importitem_batch"),
        ("products", "0007_alter_product_avg_unit_cost_alter_product_barcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="products.product",
                verbose_name="Produto (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="products.productvariant",
                verbose_name="Variante/SKU",
            ),
        ),
    ]
