# Generated by Django 5.2.10 on 2026-02-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_stockmovement_product_and_more"),
        ("products", "0009_alter_productvariant_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="products.productvariant",
                verbose_name="Variante/SKU",
            ),
        ),
    ]
