# Generated by Django 5.2.10 on 2026-02-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_stockmovement_variant"),
        ("products", "0010_alter_productvariant_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="type",
            field=models.CharField(
                choices=[
                    ("CATALOG_DIRECT", "Criação/Update de Catálogo (Completo)"),
                    ("STOCK_SYNC", "Sincronização de Estoque (SKU Only)"),
                    ("CSV_PRODUCTS", "CSV de Produtos (Legado/IA)"),
                    ("XML_NFE", "XML de NF-e (Descontinuado)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="products.productvariant",
                verbose_name="Variante/SKU",
            ),
        ),
    ]
