# Generated by Django 5.2.10 on 2026-02-17 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_importbatch_type_alter_stockmovement_variant"),
        ("tenants", "0003_alter_plan_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingassociation",
            name="import_batch",
        ),
        migrations.RemoveField(
            model_name="pendingassociation",
            name="resolved_product",
        ),
        migrations.RemoveField(
            model_name="pendingassociation",
            name="resolved_variant",
        ),
        migrations.RemoveField(
            model_name="pendingassociation",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="pendingassociation",
            name="tenant",
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="type",
            field=models.CharField(
                choices=[
                    ("CATALOG_DIRECT", "Criação/Update de Catálogo (Completo/CSV)"),
                    ("STOCK_SYNC", "Sincronização de Estoque (SKU Only/CSV)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="importitem",
            name="source",
            field=models.CharField(
                choices=[
                    ("CSV", "Importação CSV"),
                    ("API", "Integração API"),
                    ("MANUAL", "Manual"),
                ],
                default="CSV",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PROCESSING", "Processando"),
                            ("COMPLETED", "Concluído"),
                            ("FAILED", "Falha"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("log", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Exportação",
                "verbose_name_plural": "Lotes de Exportação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AdjustmentReason",
        ),
        migrations.DeleteModel(
            name="PendingAssociation",
        ),
    ]
