# Generated by Django 5.2.10 on 2026-02-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_remove_pendingassociation_import_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportbatch",
            name="export_type",
            field=models.CharField(
                choices=[("CSV", "CSV"), ("EXCEL", "Excel"), ("JSON", "JSON")],
                default="CSV",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="exportbatch",
            name="resource",
            field=models.CharField(
                choices=[("PRODUCTS", "Produtos"), ("MOVEMENTS", "Movimentações")],
                default="PRODUCTS",
                max_length=20,
            ),
        ),
    ]
