# Generated by Django 5.2.10 on 2026-02-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_exportbatch_export_type_exportbatch_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportbatch",
            name="params",
            field=models.TextField(
                blank=True, default="{}", help_text="JSON params for export filtering"
            ),
        ),
    ]
